import OpenAI from 'openai'
export const AGENTS = [['Architecture', 'Maps codebase layers and boundaries.'], ['Technical Debt', 'Scores complexity and maintainability hotspots.'], ['Risk & Cost', 'Translates debt into business priority and ROI.'], ['Refactor Planner', 'Creates concrete code scaffolds and tests.'], ['Review', 'Validates recommendation soundness and safety.']]
const lineCount = (content) => content.split(/\r?\n/).length
const framework = (files) => { const names = files.map((file) => file.path).join(' '); if (/next\.config|app\//.test(names)) return 'Next.js'; if (/vite\.config|src\/main\.(t|j)sx/.test(names)) return 'React + Vite'; if (/package\.json/.test(names)) return 'Node.js / JavaScript'; if (/requirements\.txt|pyproject/.test(names)) return 'Python'; return 'Polyglot application' }
const hotspot = (file) => { const lines = lineCount(file.content), todos = (file.content.match(/TODO|FIXME|HACK/gi) || []).length, functions = (file.content.match(/function\s+\w+|=>\s*\{/g) || []).length, score = Math.min(100, Math.round(lines / 8 + todos * 8 + Math.max(0, functions - 8) * 3)); return { path: file.path, lines, score, signals: [lines > 250 && 'large file', todos > 0 && `${todos} maintenance markers`, functions > 8 && 'high function density'].filter(Boolean) } }
const scaffold = (target) => { const name = target.path.split('/').pop().replace(/\.[^.]+$/, '') || 'Feature'; return [{ path: `src/features/${name}/${name}.ts`, content: `export type ${name}Input = { id: string }\n\nexport function create${name}(input: ${name}Input) {\n  return { ...input }\n}\n` }, { path: `src/features/${name}/${name}.test.ts`, content: `import { describe, expect, it } from 'vitest'\nimport { create${name} } from './${name}'\n\ndescribe('create${name}', () => {\n  it('keeps its contract stable', () => {\n    expect(create${name}({ id: 'demo' })).toEqual({ id: 'demo' })\n  })\n})\n` }] }
async function enhance(name, deterministic, context) {
  if (!process.env.OPENAI_API_KEY || !process.env.OPENAI_MODEL) return { data: deterministic, source: 'deterministic' }
  try { const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY }); const response = await client.responses.create({ model: process.env.OPENAI_MODEL, instructions: `You are the ${name} agent in CodeGenome AI. Improve supplied JSON without inventing facts. Return JSON only with the same fields.`, input: JSON.stringify({ deterministic, context: { repo: context.repo, filePaths: context.files.map((f) => f.path).slice(0, 25) } }) }); return { data: { ...deterministic, ...JSON.parse(response.output_text) }, source: 'openai' } } catch { return { data: deterministic, source: 'fallback' } }
}
export async function runAnalysis(repository) {
  const events = [], emit = (agent, status, rationale) => events.push({ agent, status, rationale, at: new Date().toISOString() }), { repo, files } = repository, context = { repo, files }, outcomes = {}
  const fallbackNotice = repository.fallbackReason ? `GitHub snapshot unavailable (${repository.fallbackReason}). Using a deterministic demo-safe analysis.` : `Sampled ${files.length} source files.`
  emit('Architecture', 'running', AGENTS[0][1]); outcomes.architecture = await enhance('Architecture', { framework: framework(files), layers: ['presentation', 'domain logic', 'data/integrations'], structure: repository.structure || { sampledFileCount: files.length, rootDirectories: [], languages: [], entryPoints: [] }, violations: files.filter((f) => /components?\/.+service|services?\/.+tsx/i.test(f.path)).slice(0, 3).map((f) => `${f.path}: UI and service concerns may be mixed.`), summary: fallbackNotice }, context); emit('Architecture', 'complete', 'Architecture map handed to Technical Debt.')
  emit('Technical Debt', 'running', AGENTS[1][1]); const hotspots = files.map(hotspot).filter((item) => item.score > 15).sort((a, b) => b.score - a.score).slice(0, 6), debtBase = { hotspots, totalDebtScore: Math.round(hotspots.reduce((sum, item) => sum + item.score, 0) / Math.max(hotspots.length, 1)), summary: hotspots.length ? `${hotspots.length} actionable hotspots found.` : repository.fallbackReason ? 'No repository files were available, so this is a deterministic demo-safe estimate.' : 'No major static-analysis hotspots in sampled files.' }; outcomes.debt = await enhance('Technical Debt', debtBase, context); emit('Technical Debt', 'complete', 'Debt evidence handed to Risk & Cost.')
  emit('Risk & Cost', 'running', AGENTS[2][1]); const annualCost = Math.max(250, Math.round((outcomes.debt.data.totalDebtScore || debtBase.totalDebtScore) * 18)); outcomes.cost = await enhance('Risk & Cost', { annualCost, priority: annualCost > 1200 ? 'High' : annualCost > 650 ? 'Medium' : 'Low', roiMonths: Math.max(1, Math.round(annualCost / 260)), assumption: 'Estimate uses static complexity signals and a blended engineering maintenance rate.' }, context); emit('Risk & Cost', 'complete', 'Business case handed to Refactor Planner.')
  emit('Refactor Planner', 'running', AGENTS[3][1]); const target = hotspots[0] || { path: files[0]?.path || 'src/feature.ts' }; outcomes.refactor = await enhance('Refactor Planner', { target: target.path, steps: [`Extract focused behavior from ${target.path}.`, 'Add a stable public contract.', 'Cover the contract with focused unit tests.'], scaffolds: scaffold(target), pullRequestTitle: `refactor: modularize ${target.path}` }, context); emit('Refactor Planner', 'complete', 'Scaffold handed to Review.')
  emit('Review', 'running', AGENTS[4][1]); outcomes.review = await enhance('Review', { verdict: 'Verified', checks: ['Recommendation is supported by sampled file metrics.', 'Scaffold is additive and does not alter the analyzed repository.', 'Tests cover the proposed public contract.'], caveat: repository.truncated ? 'Repository sampling limit reached; inspect the full tree before merging.' : null }, context); emit('Review', 'complete', 'Self-review completed.')
  return { repo, events, results: outcomes, source: Object.values(outcomes).some((value) => value.source === 'openai') ? 'live' : 'demo-safe' }
}
