import type { Analysis } from '../types'
import { DemoModeBadge } from './DemoModeBadge'
import { DownloadButton } from './DownloadButton'
import { RepositoryQA } from './RepositoryQA'

/**
 * Displays the completed analysis, generated scaffolds, download action, and Q&A.
 */
export function ResultsPanel({ analysis }: { analysis: Analysis }) {
  const { architecture, debt, cost, refactor, review } = analysis.results
  return <><DemoModeBadge isDemo={analysis.isDemo} /><section className="metrics"><section className="card"><span>Debt score</span><strong>{debt.data.totalDebtScore}<small>/100</small></strong></section><section className="card"><span>Estimated annual drag</span><strong>${cost.data.annualCost.toLocaleString()}</strong></section><section className="card"><span>Refactor payback</span><strong>{cost.data.roiMonths} mo.</strong></section><section className="card"><span>Review status</span><strong className="verified">{review.data.verdict}</strong></section></section>
    <section className="grid"><section className="card"><p className="eyebrow">ARCHITECTURE MAP</p><h2>{architecture.data.framework}</h2><p>{architecture.data.summary}</p><div className="tags">{architecture.data.layers.map((layer) => <span key={layer}>{layer}</span>)}</div>{architecture.data.violations.length > 0 && <ul>{architecture.data.violations.map((violation) => <li key={violation}>{violation}</li>)}</ul>}</section><section className="card"><p className="eyebrow">REPOSITORY FOOTPRINT</p><h2>{architecture.data.structure.sampledFileCount} files sampled</h2><p>{architecture.data.structure.rootDirectories.join(' / ') || 'Flat source structure'}</p><div className="tags">{architecture.data.structure.languages.map(([language, count]) => <span key={language}>{language} {count}</span>)}</div></section><section className="card"><p className="eyebrow">RISK & COST</p><h2>{cost.data.priority} priority</h2><p>{cost.data.assumption}</p><div className="bar"><i style={{ width: `${Math.min(100, debt.data.totalDebtScore)}%` }} /></div></section></section>
    <section className="card"><div className="section-head"><div><p className="eyebrow">TECHNICAL DEBT</p><h2>Evidence, not guesswork</h2></div><span>{debt.data.summary}</span></div><div className="hotspots">{debt.data.hotspots.length ? debt.data.hotspots.map((hotspot) => <article key={hotspot.path}><div><strong>{hotspot.path}</strong><p>{hotspot.signals.join(' / ') || 'complexity signal'}</p></div><b>{hotspot.score}</b><span>{hotspot.lines} lines</span></article>) : <p className="empty-state">No major static-analysis hotspots in the sampled files.</p>}</div></section>
    <section className="card"><div className="section-head"><div><p className="eyebrow">REFACTOR PLAN</p><h2>{refactor.data.pullRequestTitle}</h2></div><DownloadButton analysisId={analysis.analysisId} /></div><ol>{refactor.data.steps.map((step) => <li key={step}>{step}</li>)}</ol>{refactor.data.scaffolds.map((file) => <div className="code" key={file.path}><div><span>{file.path}</span><button onClick={() => navigator.clipboard.writeText(file.content)}>Copy</button></div><pre>{file.content}</pre></div>)}</section>
    <section className="grid"><section className="card"><p className="eyebrow">SELF-REVIEW</p><h2>{review.data.verdict}</h2><ul>{review.data.checks.map((check) => <li key={check}>{check}</li>)}</ul>{review.data.caveat && <p className="caveat">{review.data.caveat}</p>}</section><section className="card"><p className="eyebrow">REPOSITORY Q&A</p><h2>Ask the completed analysis</h2><RepositoryQA analysisId={analysis.analysisId} /></section></section>
  </>
}
