/**
 * Automated Pull Request Service for CodeGenome AI
 * Interacts with GitHub REST API to create branches, tree objects, commits, and Pull Requests.
 */

function getCleanToken(customToken) {
  if (customToken && typeof customToken === 'string') {
    const clean = customToken.trim()
    if (clean.length > 5 && !clean.startsWith('optional_') && !clean.startsWith('your_')) return clean
  }
  const token = process.env.GITHUB_TOKEN?.trim()
  if (!token || token.startsWith('optional_') || token.startsWith('your_') || token.length < 10) return null
  return token
}

function githubHeaders(token) {
  return {
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'User-Agent': 'CodeGenome-AI',
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
  }
}

/**
 * Creates a Pull Request on GitHub.
 * If write permissions exist on target repo, pushes branch directly.
 * If write permissions do NOT exist, automatically forks repo, pushes branch to user's fork, and creates cross-fork PR!
 */
export async function createPullRequest({
  owner,
  repository,
  defaultBranch = 'main',
  title,
  branch,
  body,
  files = [],
  patch = '',
  token = null,
}) {
  const cleanToken = getCleanToken(token)
  const safeBranch = branch || `codegenome/refactor-${Date.now().toString(36)}`
  const prTitle = title || `refactor(architecture): CodeGenome automated refactor`
  const prBody = body || `## CodeGenome AI Automated Refactor\n\n- **Target Repository**: ${owner}/${repository}\n- **Base Branch**: ${defaultBranch}\n- **Automated Branch**: ${safeBranch}\n\n### Summary\nIdentified technical debt and high cyclomatic complexity. This refactor extracts monolithic logic into modular units and provides test coverage.\n\n---\n*Generated by [CodeGenome AI](https://codegenome.ai)*`

  const cliCommand = `git checkout -b ${safeBranch} && git apply --whitespace=fix patch.diff`

  // 1. If no token provided or demo repo, return simulated PR preview
  if (!cleanToken || owner.toLowerCase() === 'demo') {
    return {
      success: true,
      mode: 'simulated',
      branch: safeBranch,
      baseBranch: defaultBranch,
      title: prTitle,
      body: prBody,
      prUrl: `https://github.com/${owner}/${repository}`,
      patch,
      cliCommand,
      message: 'PR patch generated! Connect your GitHub Personal Access Token (PAT) in the login menu to automatically push branches and submit live Pull Requests.',
    }
  }

  try {
    // Get authenticated user info
    let userLogin = null
    const userRes = await fetch('https://api.github.com/user', {
      headers: githubHeaders(cleanToken),
      signal: AbortSignal.timeout(8_000),
    })
    if (userRes.ok) {
      const userData = await userRes.json()
      userLogin = userData.login
    }

    // Query repository metadata and permissions
    const repoRes = await fetch(`https://api.github.com/repos/${owner}/${repository}`, {
      headers: githubHeaders(cleanToken),
      signal: AbortSignal.timeout(8_000),
    })

    if (!repoRes.ok) {
      const errBody = await repoRes.json().catch(() => ({}))
      return {
        success: true,
        mode: 'simulated',
        branch: safeBranch,
        baseBranch: defaultBranch,
        title: prTitle,
        body: prBody,
        prUrl: `https://github.com/${owner}/${repository}`,
        patch,
        cliCommand,
        message: `GitHub repository check: ${errBody.message || repoRes.statusText}. Generated in Preview Mode.`,
      }
    }

    const repoData = await repoRes.json()
    const targetBaseBranch = repoData.default_branch || defaultBranch
    const canPush = Boolean(repoData.permissions?.push || repoData.permissions?.admin)

    let targetOwner = owner
    let isCrossFork = false

    if (!canPush && userLogin) {
      // User doesn't have write access to original repo -> Fork to user's account!
      isCrossFork = true
      targetOwner = userLogin

      // Create or check fork
      const forkRes = await fetch(`https://api.github.com/repos/${owner}/${repository}/forks`, {
        method: 'POST',
        headers: githubHeaders(cleanToken),
        signal: AbortSignal.timeout(10_000),
      })
      if (forkRes.ok || forkRes.status === 202) {
        // Give GitHub a moment to establish fork ref
        await new Promise((r) => setTimeout(r, 2000))
      }
    }

    // Step A: Get reference commit of base branch from target or parent repo
    const refRes = await fetch(
      `https://api.github.com/repos/${owner}/${repository}/git/ref/heads/${encodeURIComponent(targetBaseBranch)}`,
      { headers: githubHeaders(cleanToken), signal: AbortSignal.timeout(8_000) }
    )

    if (!refRes.ok) {
      throw new Error(`Failed to resolve base branch reference '${targetBaseBranch}' on ${owner}/${repository}`)
    }

    const refData = await refRes.json()
    const baseCommitSha = refData.object.sha

    // Step B: Get base commit tree
    const commitRes = await fetch(
      `https://api.github.com/repos/${owner}/${repository}/git/commits/${baseCommitSha}`,
      { headers: githubHeaders(cleanToken), signal: AbortSignal.timeout(8_000) }
    )
    const commitData = await commitRes.json()
    const baseTreeSha = commitData.tree.sha

    // Step C: Create new Git tree with all files on target repo (user fork or main repo)
    const treePayload = {
      base_tree: baseTreeSha,
      tree: files.map((f) => ({
        path: f.path,
        mode: '100644',
        type: 'blob',
        content: f.content,
      })),
    }

    const newTreeRes = await fetch(`https://api.github.com/repos/${targetOwner}/${repository}/git/trees`, {
      method: 'POST',
      headers: { ...githubHeaders(cleanToken), 'Content-Type': 'application/json' },
      body: JSON.stringify(treePayload),
      signal: AbortSignal.timeout(8_000),
    })

    if (!newTreeRes.ok) {
      const err = await newTreeRes.json().catch(() => ({}))
      throw new Error(`Failed to create Git tree on ${targetOwner}/${repository}: ${err.message || newTreeRes.statusText}`)
    }

    const newTreeData = await newTreeRes.json()
    const newTreeSha = newTreeData.sha

    // Step D: Create Git Commit on target repo
    const newCommitRes = await fetch(`https://api.github.com/repos/${targetOwner}/${repository}/git/commits`, {
      method: 'POST',
      headers: { ...githubHeaders(cleanToken), 'Content-Type': 'application/json' },
      body: JSON.stringify({
        message: `${prTitle}\n\n${prBody}`,
        tree: newTreeSha,
        parents: [baseCommitSha],
      }),
      signal: AbortSignal.timeout(8_000),
    })

    if (!newCommitRes.ok) {
      const err = await newCommitRes.json().catch(() => ({}))
      throw new Error(`Failed to create Git commit: ${err.message || newCommitRes.statusText}`)
    }

    const newCommitData = await newCommitRes.json()
    const newCommitSha = newCommitData.sha

    // Step E: Create new branch reference on target repo
    const createRefRes = await fetch(`https://api.github.com/repos/${targetOwner}/${repository}/git/refs`, {
      method: 'POST',
      headers: { ...githubHeaders(cleanToken), 'Content-Type': 'application/json' },
      body: JSON.stringify({
        ref: `refs/heads/${safeBranch}`,
        sha: newCommitSha,
      }),
      signal: AbortSignal.timeout(8_000),
    })

    if (!createRefRes.ok) {
      const err = await createRefRes.json().catch(() => ({}))
      throw new Error(`Failed to create branch ${safeBranch}: ${err.message || createRefRes.statusText}`)
    }

    // Step F: Open Pull Request on original owner/repository
    const headRef = isCrossFork ? `${userLogin}:${safeBranch}` : safeBranch
    const prRes = await fetch(`https://api.github.com/repos/${owner}/${repository}/pulls`, {
      method: 'POST',
      headers: { ...githubHeaders(cleanToken), 'Content-Type': 'application/json' },
      body: JSON.stringify({
        title: prTitle,
        head: headRef,
        base: targetBaseBranch,
        body: prBody,
      }),
      signal: AbortSignal.timeout(8_000),
    })

    if (prRes.ok) {
      const prResult = await prRes.json()
      return {
        success: true,
        mode: 'live',
        prUrl: prResult.html_url,
        prNumber: prResult.number,
        branch: safeBranch,
        baseBranch: targetBaseBranch,
        title: prTitle,
        body: prBody,
        cliCommand,
        message: `Successfully created Pull Request #${prResult.number} on GitHub!`,
      }
    }

    // If PR creation via API had an issue, provide direct cross-fork comparison URL on GitHub
    const compareUrl = isCrossFork
      ? `https://github.com/${owner}/${repository}/compare/${targetBaseBranch}...${userLogin}:${safeBranch}`
      : `https://github.com/${owner}/${repository}/compare/${targetBaseBranch}...${safeBranch}`

    return {
      success: true,
      mode: 'live',
      prUrl: compareUrl,
      branch: safeBranch,
      baseBranch: targetBaseBranch,
      title: prTitle,
      body: prBody,
      cliCommand,
      message: `Branch pushed to ${targetOwner}/${repository}! Click 'Review and Compare' to complete Pull Request on GitHub.`,
    }
  } catch (error) {
    console.error('[PR Service] Live PR error:', error)
    return {
      success: true,
      mode: 'simulated',
      branch: safeBranch,
      baseBranch: defaultBranch,
      title: prTitle,
      body: prBody,
      prUrl: `https://github.com/${owner}/${repository}`,
      patch,
      cliCommand,
      message: `Live PR creation notice: ${error.message}. PR patch bundle is ready to download.`,
    }
  }
}
