/**
 * Automated Pull Request Service for CodeGenome AI
 * Interacts with GitHub REST API to create branches, tree objects, commits, and Pull Requests.
 */

function getCleanToken(customToken) {
  if (customToken && typeof customToken === 'string') {
    const clean = customToken.trim()
    if (clean.length > 5 && !clean.startsWith('optional_') && !clean.startsWith('your_')) return clean
  }
  const token = process.env.GITHUB_TOKEN?.trim()
  if (!token || token.startsWith('optional_') || token.startsWith('your_') || token.length < 10) return null
  return token
}

function githubHeaders(token) {
  return {
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'User-Agent': 'CodeGenome-AI',
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
  }
}

/**
 * Creates a Pull Request on GitHub.
 * If write permissions exist on target repo, pushes branch directly.
 * If write permissions do NOT exist, automatically forks repo, pushes branch to user's fork, and creates cross-fork PR!
 */
export async function createPullRequest({
  owner,
  repository,
  defaultBranch = 'main',
  title,
  branch,
  body,
  files = [],
  patch = '',
  token = null,
  user = null,
}) {
  const cleanToken = getCleanToken(token)
  const safeBranch = branch || `codegenome/refactor-${Date.now().toString(36)}`
  const prTitle = title || `refactor(architecture): CodeGenome automated refactor`
  const prBody = body || `## CodeGenome AI Automated Refactor\n\n- **Target Repository**: ${owner}/${repository}\n- **Base Branch**: ${defaultBranch}\n- **Automated Branch**: ${safeBranch}\n\n### Summary\nIdentified technical debt and high cyclomatic complexity. This refactor extracts monolithic logic into modular units and provides test coverage.\n\n---\n*Generated by [CodeGenome AI](https://codegenome.ai)*`

  const cliCommand = `git checkout -b ${safeBranch} && git apply --whitespace=fix patch.diff`
  const userLogin = user?.login || 'arulraghav07'
  let apiUserLogin = userLogin

  // If live GitHub token is present, attempt live push & pull request creation via GitHub REST API
  if (cleanToken && owner.toLowerCase() !== 'demo') {
    try {
      // Get authenticated user info
      const userRes = await fetch('https://api.github.com/user', {
        headers: githubHeaders(cleanToken),
        signal: AbortSignal.timeout(8_000),
      })
      if (!userRes.ok) {
        throw new Error(`Failed to verify user token (${userRes.status})`)
      }
      const userData = await userRes.json()
      apiUserLogin = userData.login

      // Query repository metadata and permissions
      const repoRes = await fetch(`https://api.github.com/repos/${owner}/${repository}`, {
        headers: githubHeaders(cleanToken),
        signal: AbortSignal.timeout(8_000),
      })
      if (!repoRes.ok) {
        throw new Error(`Failed to fetch metadata for ${owner}/${repository} (${repoRes.status})`)
      }
      const repoData = await repoRes.json()
      const targetBaseBranch = repoData.default_branch || defaultBranch
      const canPush = Boolean(repoData.permissions?.push || repoData.permissions?.admin)

      let targetOwner = owner
      let isCrossFork = false

      if (!canPush && apiUserLogin) {
        isCrossFork = true
        targetOwner = apiUserLogin

        // Fork repository to user's account
        const forkRes = await fetch(`https://api.github.com/repos/${owner}/${repository}/forks`, {
          method: 'POST',
          headers: githubHeaders(cleanToken),
          signal: AbortSignal.timeout(10_000),
        })
        if (!forkRes.ok && forkRes.status !== 202) {
          throw new Error(`Failed to initiate repository fork (${forkRes.status})`)
        }

        // Poll up to 6 times (up to 12s) to ensure fork repository is created and ready
        let forkReady = false
        for (let attempt = 0; attempt < 6; attempt++) {
          await new Promise((r) => setTimeout(r, 2000))
          const checkFork = await fetch(`https://api.github.com/repos/${targetOwner}/${repository}`, {
            headers: githubHeaders(cleanToken),
            signal: AbortSignal.timeout(5_000),
          })
          if (checkFork.ok) {
            forkReady = true
            break
          }
        }

        if (!forkReady) {
          throw new Error(`Fork repository ${targetOwner}/${repository} creation timed out.`)
        }
      }

      // Get reference commit of base branch
      const refRes = await fetch(
        `https://api.github.com/repos/${owner}/${repository}/git/ref/heads/${encodeURIComponent(targetBaseBranch)}`,
        { headers: githubHeaders(cleanToken), signal: AbortSignal.timeout(8_000) }
      )
      if (!refRes.ok) {
        throw new Error(`Failed to get ref commit for base branch ${targetBaseBranch} (${refRes.status})`)
      }
      const refData = await refRes.json()
      const baseCommitSha = refData.object.sha

      // Get base commit tree
      const commitRes = await fetch(
        `https://api.github.com/repos/${owner}/${repository}/git/commits/${baseCommitSha}`,
        { headers: githubHeaders(cleanToken), signal: AbortSignal.timeout(8_000) }
      )
      if (!commitRes.ok) {
        throw new Error(`Failed to fetch base commit details (${commitRes.status})`)
      }
      const commitData = await commitRes.json()
      const baseTreeSha = commitData.tree.sha

      // Create new Git tree with all files
      const treePayload = {
        base_tree: baseTreeSha,
        tree: files.map((f) => ({
          path: f.path,
          mode: '100644',
          type: 'blob',
          content: f.content,
        })),
      }

      const newTreeRes = await fetch(`https://api.github.com/repos/${targetOwner}/${repository}/git/trees`, {
        method: 'POST',
        headers: { ...githubHeaders(cleanToken), 'Content-Type': 'application/json' },
        body: JSON.stringify(treePayload),
        signal: AbortSignal.timeout(8_000),
      })
      if (!newTreeRes.ok) {
        throw new Error(`Failed to build file tree (${newTreeRes.status})`)
      }
      const newTreeData = await newTreeRes.json()
      const newTreeSha = newTreeData.sha

      // Create Git Commit
      const newCommitRes = await fetch(`https://api.github.com/repos/${targetOwner}/${repository}/git/commits`, {
        method: 'POST',
        headers: { ...githubHeaders(cleanToken), 'Content-Type': 'application/json' },
        body: JSON.stringify({
          message: `${prTitle}\n\n${prBody}`,
          tree: newTreeSha,
          parents: [baseCommitSha],
        }),
        signal: AbortSignal.timeout(8_000),
      })
      if (!newCommitRes.ok) {
        throw new Error(`Failed to construct commit (${newCommitRes.status})`)
      }
      const newCommitData = await newCommitRes.json()
      const newCommitSha = newCommitData.sha

      // Create new branch reference
      const createRefRes = await fetch(`https://api.github.com/repos/${targetOwner}/${repository}/git/refs`, {
        method: 'POST',
        headers: { ...githubHeaders(cleanToken), 'Content-Type': 'application/json' },
        body: JSON.stringify({
          ref: `refs/heads/${safeBranch}`,
          sha: newCommitSha,
        }),
        signal: AbortSignal.timeout(8_000),
      })
      if (!createRefRes.ok) {
        const errJson = await createRefRes.json().catch(() => ({}))
        if (errJson.message?.includes('already exists')) {
          throw new Error(`Branch ref 'refs/heads/${safeBranch}' already exists. Please supply a different branch name.`)
        }
        throw new Error(`Failed to create branch reference (${createRefRes.status})`)
      }

      // Allow 2.5 seconds for GitHub's internal database replicas to sync the new branch 
      // before we attempt to create a PR or redirect the user, preventing "Branch not found" errors.
      console.log('[PR Service] Waiting for GitHub replication sync...')
      await new Promise(resolve => setTimeout(resolve, 2500))

      // Open Pull Request on original owner/repository
      const headRef = isCrossFork ? `${apiUserLogin}:${safeBranch}` : safeBranch
      console.log(`[PR Service] Creating Pull Request. Head: ${headRef}, Base: ${targetBaseBranch}`)
      
      const prRes = await fetch(`https://api.github.com/repos/${owner}/${repository}/pulls`, {
        method: 'POST',
        headers: { ...githubHeaders(cleanToken), 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: prTitle,
          head: headRef,
          base: targetBaseBranch,
          body: prBody,
        }),
        signal: AbortSignal.timeout(8_000),
      })

      if (prRes.ok) {
        const prResult = await prRes.json()
        console.log(`[PR Service] PR Created successfully: ${prResult.html_url}`)
        return {
          success: true,
          mode: 'live',
          pushed: true,
          prUrl: prResult.html_url,
          prNumber: prResult.number,
          branch: safeBranch,
          baseBranch: targetBaseBranch,
          title: prTitle,
          body: prBody,
          cliCommand,
          message: `Successfully created Pull Request #${prResult.number} on GitHub!`,
        }
      } else {
        const errJson = await prRes.json().catch(() => ({}))
        const errMsg = errJson.message || 'Unknown GitHub API error'
        const errDetails = errJson.errors ? errJson.errors.map(e => e.message).join(', ') : ''
        
        console.error(`[PR Service] PR Creation failed: ${prRes.status} ${errMsg} ${errDetails}`)
        
        // Always fall back to returning the compare URL so the user is redirected to GitHub UI
        console.log('[PR Service] Returning compare URL due to Validation Failed')
        const compareUrl = `https://github.com/${owner}/${repository}/compare/${targetBaseBranch}...${headRef}?expand=1`
        return {
          success: true,
          mode: 'live',
          pushed: true,
          prUrl: compareUrl,
          branch: safeBranch,
          baseBranch: targetBaseBranch,
          title: prTitle,
          body: prBody,
          cliCommand,
          message: `Branch '${safeBranch}' successfully created and pushed to GitHub! Click to review and open your Pull Request.`,
        }
      }
    } catch (error) {
      console.warn('[PR Service] Live API attempt fallback:', error.message)
      return {
        success: true,
        mode: 'ready',
        pushed: false,
        prUrl: null,
        branch: safeBranch,
        baseBranch: targetBaseBranch,
        title: prTitle,
        body: prBody,
        patch,
        cliCommand,
        message: `Changes prepared for ${owner}/${repository}! To create a live Pull Request on GitHub, GitHub requires authorization (PAT) to fork and push the branch to your account.`,
      }
    }
  }

  // Fallback when live API push token is restricted or unavailable:
  return {
    success: true,
    mode: 'ready',
    pushed: false,
    prUrl: null,
    branch: safeBranch,
    baseBranch: defaultBranch,
    title: prTitle,
    body: prBody,
    patch,
    cliCommand,
    message: `Refactor branch '${safeBranch}' prepared for ${owner}/${repository}! Enter a GitHub Personal Access Token to fork and push automatically, or use the Git CLI patch below.`,
  }
}
