/**
 * Automated Pull Request Service for CodeGenome AI
 * Interacts with GitHub REST API to create branches, tree objects, commits, and Pull Requests.
 */

function getCleanToken(customToken) {
  if (customToken && typeof customToken === 'string') {
    const clean = customToken.trim()
    if (clean.length > 5 && !clean.startsWith('optional_') && !clean.startsWith('your_')) return clean
  }
  const token = process.env.GITHUB_TOKEN?.trim()
  if (!token || token.startsWith('optional_') || token.startsWith('your_') || token.length < 10) return null
  return token
}

function githubHeaders(token) {
  return {
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'User-Agent': 'CodeGenome-AI',
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
  }
}

/**
 * Creates a Pull Request on GitHub.
 * If write permissions exist, executes live Git Tree + Commit + Ref + PR creation.
 * Otherwise, generates a complete PR Preview with ready-to-apply patch and CLI commands.
 */
export async function createPullRequest({
  owner,
  repository,
  defaultBranch = 'main',
  title,
  branch,
  body,
  files = [],
  patch = '',
  token = null,
}) {
  const cleanToken = getCleanToken(token)
  const safeBranch = branch || `codegenome/refactor-${Date.now().toString(36)}`
  const prTitle = title || `refactor(architecture): CodeGenome automated refactor`
  const prBody = body || `## CodeGenome AI Automated Refactor\n\n- **Target Repository**: ${owner}/${repository}\n- **Base Branch**: ${defaultBranch}\n- **Automated Branch**: ${safeBranch}\n\n### Summary\nIdentified technical debt and high cyclomatic complexity. This refactor extracts monolithic logic into modular units and provides test coverage.\n\n---\n*Generated by [CodeGenome AI](https://codegenome.ai)*`

  const cliCommand = `git checkout -b ${safeBranch} && git apply --whitespace=fix patch.diff`

  // 1. If no token provided or demo repo, return simulated PR preview
  if (!cleanToken || owner.toLowerCase() === 'demo') {
    return {
      success: true,
      mode: 'simulated',
      branch: safeBranch,
      baseBranch: defaultBranch,
      title: prTitle,
      body: prBody,
      prUrl: `https://github.com/${owner}/${repository}/compare/${defaultBranch}...${safeBranch}`,
      patch,
      cliCommand,
      message: 'PR bundle generated in Preview Mode. Connect a GitHub token with write access to submit directly to GitHub.',
    }
  }

  // 2. Query repository metadata and permissions
  try {
    const repoRes = await fetch(`https://api.github.com/repos/${owner}/${repository}`, {
      headers: githubHeaders(cleanToken),
      signal: AbortSignal.timeout(8_000),
    })

    if (!repoRes.ok) {
      const errBody = await repoRes.json().catch(() => ({}))
      return {
        success: true,
        mode: 'simulated',
        branch: safeBranch,
        baseBranch: defaultBranch,
        title: prTitle,
        body: prBody,
        prUrl: `https://github.com/${owner}/${repository}/compare/${defaultBranch}...${safeBranch}`,
        patch,
        cliCommand,
        message: `GitHub repository check: ${errBody.message || repoRes.statusText}. Generated in Preview Mode.`,
      }
    }

    const repoData = await repoRes.json()
    const targetBaseBranch = repoData.default_branch || defaultBranch
    const canPush = Boolean(repoData.permissions?.push || repoData.permissions?.admin)

    if (!canPush) {
      // User does not have direct write/push access to target repository
      return {
        success: true,
        mode: 'simulated',
        branch: safeBranch,
        baseBranch: targetBaseBranch,
        title: prTitle,
        body: prBody,
        prUrl: `https://github.com/${owner}/${repository}/compare/${targetBaseBranch}...${safeBranch}`,
        patch,
        cliCommand,
        message: `Your GitHub account has read access to ${owner}/${repository}, but write permissions are required to push new branches directly. You can apply the patch locally or create a fork.`,
      }
    }

    // 3. User has push access! Execute live Git API workflow
    // Step A: Get reference commit of base branch
    const refRes = await fetch(
      `https://api.github.com/repos/${owner}/${repository}/git/ref/heads/${encodeURIComponent(targetBaseBranch)}`,
      { headers: githubHeaders(cleanToken), signal: AbortSignal.timeout(8_000) }
    )

    if (!refRes.ok) {
      throw new Error(`Failed to resolve base branch reference ${targetBaseBranch}`)
    }

    const refData = await refRes.json()
    const baseCommitSha = refData.object.sha

    // Step B: Get base commit tree
    const commitRes = await fetch(
      `https://api.github.com/repos/${owner}/${repository}/git/commits/${baseCommitSha}`,
      { headers: githubHeaders(cleanToken), signal: AbortSignal.timeout(8_000) }
    )
    const commitData = await commitRes.json()
    const baseTreeSha = commitData.tree.sha

    // Step C: Create new Git tree with all files
    const treePayload = {
      base_tree: baseTreeSha,
      tree: files.map((f) => ({
        path: f.path,
        mode: '100644',
        type: 'blob',
        content: f.content,
      })),
    }

    const newTreeRes = await fetch(`https://api.github.com/repos/${owner}/${repository}/git/trees`, {
      method: 'POST',
      headers: { ...githubHeaders(cleanToken), 'Content-Type': 'application/json' },
      body: JSON.stringify(treePayload),
      signal: AbortSignal.timeout(8_000),
    })

    if (!newTreeRes.ok) {
      const err = await newTreeRes.json().catch(() => ({}))
      throw new Error(`Failed to create Git tree: ${err.message || newTreeRes.statusText}`)
    }

    const newTreeData = await newTreeRes.json()
    const newTreeSha = newTreeData.sha

    // Step D: Create Git Commit
    const newCommitRes = await fetch(`https://api.github.com/repos/${owner}/${repository}/git/commits`, {
      method: 'POST',
      headers: { ...githubHeaders(cleanToken), 'Content-Type': 'application/json' },
      body: JSON.stringify({
        message: `${prTitle}\n\n${prBody}`,
        tree: newTreeSha,
        parents: [baseCommitSha],
      }),
      signal: AbortSignal.timeout(8_000),
    })

    if (!newCommitRes.ok) {
      const err = await newCommitRes.json().catch(() => ({}))
      throw new Error(`Failed to create Git commit: ${err.message || newCommitRes.statusText}`)
    }

    const newCommitData = await newCommitRes.json()
    const newCommitSha = newCommitData.sha

    // Step E: Create new branch reference
    const createRefRes = await fetch(`https://api.github.com/repos/${owner}/${repository}/git/refs`, {
      method: 'POST',
      headers: { ...githubHeaders(cleanToken), 'Content-Type': 'application/json' },
      body: JSON.stringify({
        ref: `refs/heads/${safeBranch}`,
        sha: newCommitSha,
      }),
      signal: AbortSignal.timeout(8_000),
    })

    if (!createRefRes.ok) {
      const err = await createRefRes.json().catch(() => ({}))
      throw new Error(`Failed to create branch ${safeBranch}: ${err.message || createRefRes.statusText}`)
    }

    // Step F: Open Pull Request
    const prRes = await fetch(`https://api.github.com/repos/${owner}/${repository}/pulls`, {
      method: 'POST',
      headers: { ...githubHeaders(cleanToken), 'Content-Type': 'application/json' },
      body: JSON.stringify({
        title: prTitle,
        head: safeBranch,
        base: targetBaseBranch,
        body: prBody,
      }),
      signal: AbortSignal.timeout(8_000),
    })

    if (!prRes.ok) {
      const err = await prRes.json().catch(() => ({}))
      throw new Error(`Failed to create Pull Request: ${err.message || prRes.statusText}`)
    }

    const prResult = await prRes.json()

    return {
      success: true,
      mode: 'live',
      prUrl: prResult.html_url,
      prNumber: prResult.number,
      branch: safeBranch,
      baseBranch: targetBaseBranch,
      title: prTitle,
      body: prBody,
      cliCommand,
      message: `Successfully created Pull Request #${prResult.number} on GitHub!`,
    }
  } catch (error) {
    console.error('[PR Service] Live PR error:', error)
    // Fall back to preview mode with the patch and error explanation
    return {
      success: true,
      mode: 'simulated',
      branch: safeBranch,
      baseBranch: defaultBranch,
      title: prTitle,
      body: prBody,
      prUrl: `https://github.com/${owner}/${repository}/compare/${defaultBranch}...${safeBranch}`,
      patch,
      cliCommand,
      message: `Live PR creation encountered an issue: ${error.message}. PR bundle generated in Preview Mode.`,
    }
  }
}
